name: Documentation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-docs:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-rdme
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-rdme
      - name: Check README.md is up-to-date
        run: cargo rdme --check
